"""DynamoDB persistence for linking a Telegram chat to an OBLIGRA user.

Telegram's webhook calls this backend directly, with no OBLIGRA JWT
attached (Telegram has no knowledge of our auth system). Before any
message from a given `chat_id` can be attributed to an OBLIGRA user, that
chat must be linked to a `user_id` — this module implements that linking
flow with two small tables:

  - link codes table (`obligra-telegram-link-codes`, PK `code`): a
    short-lived, single-use code generated by an authenticated OBLIGRA
    user (see `POST /api/integrations/telegram/link-code`) and then sent
    to the bot as `/start <code>`. Consuming a code is a conditional
    delete keyed on the code still existing, so a code can never be used
    twice even under concurrent requests.
  - links table (`obligra-telegram-links`, PK `chat_id`): the permanent
    mapping from a Telegram chat to the OBLIGRA user it's linked to,
    written once a code is successfully consumed.

Both tables intentionally have no GSIs — every lookup here is always by
the table's own primary key (`code` or `chat_id`), so a GSI would add
cost without adding any capability.
"""

import logging
import secrets
from datetime import UTC, datetime, timedelta
from functools import lru_cache

import boto3
from botocore.exceptions import BotoCoreError, ClientError

from app.config import get_settings

logger = logging.getLogger(__name__)


class DynamoDBError(RuntimeError):
    """Raised when a DynamoDB read or write fails."""


@lru_cache
def _get_resource():
    settings = get_settings()
    return boto3.resource("dynamodb", region_name=settings.aws_region)


def _link_codes_table():
    settings = get_settings()
    return _get_resource().Table(settings.dynamodb_telegram_link_codes_table)


def _links_table():
    settings = get_settings()
    return _get_resource().Table(settings.dynamodb_telegram_links_table)


def create_link_code(user_id: str) -> tuple[str, str]:
    """Generate a new single-use linking code for `user_id`.

    Returns `(code, expires_at)`. The code is short (6 characters, drawn
    from an unambiguous alphabet with no 0/O/1/I) so a user can type it
    into Telegram easily, while `secrets.choice` keeps it unguessable
    enough for a code that's only valid for a few minutes and consumed
    exactly once.
    """
    settings = get_settings()
    alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
    code = "".join(secrets.choice(alphabet) for _ in range(6))
    now = datetime.now(UTC)
    expires_at = now + timedelta(minutes=settings.telegram_link_code_ttl_minutes)

    item = {
        "code": code,
        "user_id": user_id,
        "created_at": now.isoformat(),
        "expires_at": expires_at.isoformat(),
    }
    try:
        _link_codes_table().put_item(Item=item)
    except (BotoCoreError, ClientError) as exc:
        raise DynamoDBError(f"Failed to create link code: {exc}") from exc

    return code, item["expires_at"]


def consume_link_code(code: str) -> str | None:
    """Atomically consume a link code and return the `user_id` it belongs to.

    Returns `None` if the code doesn't exist or has already been used —
    both cases look identical to the caller so a guesser can't
    distinguish "wrong code" from "code already used" by timing or
    response shape. Also returns `None` (without linking) if the code has
    expired, and opportunistically deletes it in that case so expired
    codes don't linger.

    The delete is conditioned on the code still existing so that two
    concurrent `/start <code>` requests for the same code can't both
    succeed — only one delete wins the race, and that one's caller is the
    only one who gets a `user_id` back.
    """
    table = _link_codes_table()

    try:
        response = table.get_item(Key={"code": code})
    except (BotoCoreError, ClientError) as exc:
        raise DynamoDBError(f"Failed to look up link code: {exc}") from exc

    item = response.get("Item")
    if item is None:
        return None

    expires_at = datetime.fromisoformat(item["expires_at"])
    if datetime.now(UTC) >= expires_at:
        try:
            table.delete_item(Key={"code": code})
        except (BotoCoreError, ClientError):
            logger.warning("Failed to clean up expired link code %s", code)
        return None

    try:
        table.delete_item(Key={"code": code}, ConditionExpression="attribute_exists(#c)", ExpressionAttributeNames={"#c": "code"})
    except ClientError as exc:
        if exc.response.get("Error", {}).get("Code") == "ConditionalCheckFailedException":
            # Someone else consumed it first.
            return None
        raise DynamoDBError(f"Failed to consume link code: {exc}") from exc
    except BotoCoreError as exc:
        raise DynamoDBError(f"Failed to consume link code: {exc}") from exc

    return item["user_id"]


def link_chat_to_user(chat_id: str, user_id: str) -> None:
    """Record that `chat_id` is linked to `user_id`.

    Overwrites any previous link for this chat — re-running `/start
    <code>` with a fresh code re-links the chat to whichever account
    generated that code, which is the expected behavior if a chat is
    reused by a different OBLIGRA account later.
    """
    item = {
        "chat_id": chat_id,
        "user_id": user_id,
        "linked_at": datetime.now(UTC).isoformat(),
    }
    try:
        _links_table().put_item(Item=item)
    except (BotoCoreError, ClientError) as exc:
        raise DynamoDBError(f"Failed to link Telegram chat: {exc}") from exc


def get_user_id_for_chat(chat_id: str) -> str | None:
    """Return the OBLIGRA `user_id` linked to `chat_id`, or None if unlinked."""
    try:
        response = _links_table().get_item(Key={"chat_id": chat_id})
    except (BotoCoreError, ClientError) as exc:
        raise DynamoDBError(f"Failed to look up Telegram chat link: {exc}") from exc

    item = response.get("Item")
    return item["user_id"] if item is not None else None


# --- In-memory /login brute-force throttling -------------------------------
#
# The web app's POST /auth/login has no rate limiting either (see
# app/routers/auth.py), but that endpoint at least requires the caller to
# already know a registered email. The Telegram /login command is reachable
# by anyone who can open a chat with the bot, so it gets its own lightweight
# per-chat attempt counter to slow down guessing. This is intentionally
# in-process memory, not DynamoDB — it only needs to survive within a single
# App Runner instance's uptime, and adding a table/GSI for something this
# small would be disproportionate. A restart clears all counters, which is
# an acceptable tradeoff (fails open to "allow", never fails closed and
# locks someone out permanently).
_LOGIN_ATTEMPTS: dict[str, list[datetime]] = {}
_LOGIN_MAX_ATTEMPTS = 5
_LOGIN_WINDOW = timedelta(minutes=15)


def is_login_rate_limited(chat_id: str) -> bool:
    """Return True if `chat_id` has made too many /login attempts recently."""
    now = datetime.now(UTC)
    attempts = [ts for ts in _LOGIN_ATTEMPTS.get(chat_id, []) if now - ts < _LOGIN_WINDOW]
    _LOGIN_ATTEMPTS[chat_id] = attempts
    return len(attempts) >= _LOGIN_MAX_ATTEMPTS


def record_login_attempt(chat_id: str) -> None:
    """Record a /login attempt (successful or not) for `chat_id`'s rate limit."""
    now = datetime.now(UTC)
    attempts = [ts for ts in _LOGIN_ATTEMPTS.get(chat_id, []) if now - ts < _LOGIN_WINDOW]
    attempts.append(now)
    _LOGIN_ATTEMPTS[chat_id] = attempts
